### ISSUE TITLE
Logging call test is still randomly failing

### ISSUE THREAD

**Issue by colinxfleming** [colinxfleming/dcaf_case_management#700]
Need to rewrite to be HEAVY on `has_x` methods, per @Kevin-Wei 's suggestion.

**Comment by colinxfleming** [comment]
Dashboard integration test too

**Comment by colinxfleming** [comment]
FAIL["test_0001_should update Call Lists", #<Class:0x000000067e0198>, 108.14871252099692]
 test_0001_should update Call Lists#RecordCallTest::Home Page Call Actions (108.15s)
        Expected false to be truthy.
        test/integration/record_call_test.rb:46:in `block (3 levels) in <class:RecordCallTest>'
        test/integration/record_call_test.rb:45:in `block (2 levels) in <class:RecordCallTest>'
