### ISSUE TITLE
Can't run tests (using Docker setup)

### ISSUE THREAD

**Issue by janinedog** [colinxfleming/dcaf_case_management#901]
* **What are we trying to do?**

Run the tests for the app.

* **What feature or behavior is this required for?**

Everything! :)

* **How could we solve this issue? (Not knowing is okay!)**

Make it work.  ;)

* **Anything else?**

Here's the commands I'm running and what's happening:

```
[jcostanzo @ oakm011401301 - ~/dcaf_case_management] -> docker-compose run web rake test
rake aborted!
LoadError: cannot load such file -- simplecov
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/src/app/test/test_helper.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/src/app/test/controllers/accountants_controller_test.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/test_unit/sub_test_task.rb:114:in `each'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/test_unit/sub_test_task.rb:113:in `each'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => test:run
(See full trace by running task with --trace)
```

```
[jcostanzo @ oakm011401301 - ~/dcaf_case_management] -> docker-compose run web bundle install
There was an error while trying to write to `/usr/local/bundle/config`. It is likely that you need to grant write permissions for that path.
```

**Comment by colinxfleming** [comment]
This is a weird one! @DarthHater as our resident God of Docker, have you seen this before? The key thing seems to be the last error in @janinedog 's post above.
